ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:
:toc-placement!:

= midPoint custom REST-like overlay

toc::[]

[NOTE]
Term "REST" is used as usual in the industry but not in the strict REST meaning.
Sorry about that.

Example of a midPoint overlay project that implements a custom REST service.
The current version is based on CXF and JAX-RS.
Early experimental Spring MVC version is described at the end of this document.

The service is implemented by link:src/main/java/com/example/midpoint/service/ExampleRestService.java[ExampleRestService] class.
Two necessary Spring context files are in `resources` directory.

This project is an adaptation (with some simplifications) of https://github.com/Evolveum/midpoint-overlay-example[midpoint-custom-service].
Head of the master normally follows the current development version of midPoint.
See https://github.com/Evolveum/midpoint-custom-rest-service/tree/v4.2[tag v4.2] for the last stable version.

See also README from the https://github.com/Evolveum/midpoint-overlay-example[basic overlay example],
including also https://github.com/Evolveum/midpoint-overlay-example/blob/master/doc/overlay-development.adoc[midPoint Overlay development] notes.
Check also https://wiki.evolveum.com/display/midPoint/Customization+With+Overlay+Project[related wiki page].

== Building and running

Use JDK 11 for building and running this overlay.
To build the example run `mvn clean package`.
The final `midpoint.war` will be built in `target`.
It can be run directly as executable JAR:

----
java -jar target/midpoint.war
----

Alternatively you may deploy the WAR to the Tomcat, but this option is no longer supported.
The web service will be listening at: http://localhost:8080/midpoint/ws/my-ext/rest-example

Deploy that WAR to the Tomcat.
The REST service is set up under http://localhost:8080/midpoint/ws/my-ext/rest-example.

== Testing

To return user(s) with e-mail address `jack@caribbean.com` try:

// Currently not usable because of MID-6654
//* Pointing a browser to the URL: http://localhost:8080/midpoint/ws/my-ext/rest-example/users/mail/jack@caribbean.com
//and entering `administrator` name and password.

* Running cURL command (by default returns XML):
+
----
curl -v --user "administrator:5ecr3t" \
  http://localhost:8080/midpoint/ws/my-ext/rest-example/users/mail/jack@caribbean.com
----

* or HTTPie command (returns JSON because of `-j` flag):
+
----
http -jv http://localhost:8080/midpoint/ws/my-ext/rest-example/users/mail/jack@caribbean.com \
  -a administrator:5ecr3t
----

== Technical notes

[NOTE]
Subject to change during 4.2 development.

Previous to 4.2, CXF servlet was configured directly in midPoint `+/ws/*+` mapping.
With 4.2 this is no longer true and `+/ws/*+` is used for REST service (just as `/rest` and `/api`).
See https://wiki.evolveum.com/display/midPoint/REST+API[REST API] on our wiki for more.

This overlay sets up CXF servlet on `+/ws/my-ext/*+`.
If colliding mapping path was chosen (like `+/ws/*+`) CXF would completely take over this sub-context.
This would break some midPoint internals like node management that uses `/ws` mapping.

We could map the servlet to `+/my-ws/*+` to avoid any collisions as well, but this would be considered
https://wiki.evolveum.com/display/midPoint/Flexible+Authentication+Configuration#FlexibleAuthenticationConfiguration-Authenticationchannel[default GUI channel].
As such, it would not work with basic authentication.
If `+/ws/my-ext/*+` is used, it does not collide with paths under `/ws`, neither does it take over `/ws` completely.
At the same time it will be considered REST channel now thanks to `+/ws/my-ext/*+` pattern
and basic authentication can be used.

https://github.com/Evolveum/midpoint-custom-service[SOAP overlay example] uses different approach
and goes around flexible authentication.

== Recommendations wrap-up

* Set up CXF servlet on a unique sub-path under `/ws/` (or `/api/` or `/rest/`).
This way you will not disrupt existing built-in services and you'll still get REST channel authentication.

* Alternatively, go for Spring MVC and just add another REST controller.
Set up `@RequestMapping("/ws/<sub-path>")` under any of the paths supporting REST channel,
but try not to collide with existing services by choosing distinct sub-path.
This will probably be the future of this overlay example as well, for now it's in an experimental phase.

== Experimental Spring MVC based REST controller

With Spring MVC REST already configured for midPoint 4.2 it is easy to set up new REST controller and operations.
However, due to freshness of this approach and minimal testing this part is considered *experimental and unsupported*.

You can test Spring MVC based REST by:

// Currently not usable because of MID-6654
//* Pointing a browser to the URL: http://localhost:8080/midpoint/ws/my-rest/users/mail/jack@caribbean.com
//and entering `administrator` name and password.

* Running cURL command (by default returns XML):
+
----
curl -v --user "administrator:5ecr3t" \
  http://localhost:8080/midpoint/ws/my-rest/users/mail/jack@caribbean.com
----

* or HTTPie command (returns JSON because of `-j` flag):
+
----
http -jv http://localhost:8080/midpoint/ws/my-rest/users/mail/jack@caribbean.com \
  -a administrator:5ecr3t
----

Whole implementation is in link:src/main/java/com/example/midpoint/service/ExampleRestController.java[ExampleRestController].
Class extends from https://github.com/Evolveum/midpoint/blob/master/model/rest-impl/src/main/java/com/evolveum/midpoint/rest/impl/AbstractRestController.java[AbstractRestController]
from midPoint to utilize existing common methods.
This is convenient but it may change in the future as it is not officially public API.

If this way is used no additional CXF dependency and configuration is necessary.
Map controllers under URL patterns using the REST channel, multiple mappings can be used,
for examples check https://github.com/Evolveum/midpoint/blob/master/model/rest-impl/src/main/java/com/evolveum/midpoint/rest/impl/ModelRestController.java[ModelRestController.java].
