= midpoint-custom-rest-overlay

Example of a midPoint overlay project that implements a custom REST service.

The service is implemented by ExampleRestService class.
Two necessary Spring context files are in "resources" directory.

This project is an adaptation (with some simplifications) of https://github.com/Evolveum/midpoint-overlay-example[midpoint-custom-service].
It is based on midPoint 4.1.

== Building and running

To build the example run:
----
mvn package
----

The final `midpoint.war` will be built in `target`.

Deploy that WAR to the Tomcat.
The service will be listening at http://localhost:8080/midpoint/ws/rest-example.

To return user(s) with e-mail address `jack@caribbean.com` try:

* pointing a browser to the URL: http://localhost:8080/midpoint/ws/rest-example/users/mail/jack@caribbean.com
* running cURL command (by default returns XML):
+
----
curl -v --user "administrator:5ecr3t" \
  http://localhost:8080/midpoint/ws/rest-example/users/mail/jack@caribbean.com
----
* or HTTPie command (this requests JSON and as of this writing it fails writing the response):
+
----
http -jv http://localhost:8080/midpoint/ws/rest-example/users/mail/x \
  -a administrator:5ecr3t
----

See https://wiki.evolveum.com/display/midPoint/Customization+With+Overlay+Project
for more details about midPoint overlay projects.
